//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: Protocol.proto
namespace ai.pkr.metabots.remote
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Props")]
  public partial class Props : global::ProtoBuf.IExtensible
  {
    public Props() {}
    
    private readonly global::System.Collections.Generic.List<string> _Names = new global::System.Collections.Generic.List<string>();
    [global::ProtoBuf.ProtoMember(1, Name=@"Names", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<string> Names
    {
      get { return _Names; }
    }
  
    private readonly global::System.Collections.Generic.List<string> _Values = new global::System.Collections.Generic.List<string>();
    [global::ProtoBuf.ProtoMember(2, Name=@"Values", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<string> Values
    {
      get { return _Values; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PokerAction")]
  public partial class PokerAction : global::ProtoBuf.IExtensible
  {
    public PokerAction() {}
    
    private ai.pkr.metabots.remote.Ak _Kind;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"Kind", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ai.pkr.metabots.remote.Ak Kind
    {
      get { return _Kind; }
      set { _Kind = value; }
    }
    private int _Position;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"Position", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public int Position
    {
      get { return _Position; }
      set { _Position = value; }
    }
    private double _Amount;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"Amount", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public double Amount
    {
      get { return _Amount; }
      set { _Amount = value; }
    }
    private string _Cards;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"Cards", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string Cards
    {
      get { return _Cards; }
      set { _Cards = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"DeckDescriptor")]
  public partial class DeckDescriptor : global::ProtoBuf.IExtensible
  {
    public DeckDescriptor() {}
    
    private string _Name;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"Name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string Name
    {
      get { return _Name; }
      set { _Name = value; }
    }
    private readonly global::System.Collections.Generic.List<string> _CardNames = new global::System.Collections.Generic.List<string>();
    [global::ProtoBuf.ProtoMember(2, Name=@"CardNames", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<string> CardNames
    {
      get { return _CardNames; }
    }
  
    private readonly global::System.Collections.Generic.List<ulong> _CardSets = new global::System.Collections.Generic.List<ulong>();
    [global::ProtoBuf.ProtoMember(3, Name=@"CardSets", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<ulong> CardSets
    {
      get { return _CardSets; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GameDefinition")]
  public partial class GameDefinition : global::ProtoBuf.IExtensible
  {
    public GameDefinition() {}
    
    private string _Name;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"Name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string Name
    {
      get { return _Name; }
      set { _Name = value; }
    }
    private int _RoundsCount;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"RoundsCount", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public int RoundsCount
    {
      get { return _RoundsCount; }
      set { _RoundsCount = value; }
    }
    private int _MinPlayers;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"MinPlayers", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public int MinPlayers
    {
      get { return _MinPlayers; }
      set { _MinPlayers = value; }
    }
    private int _MaxPlayers;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"MaxPlayers", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public int MaxPlayers
    {
      get { return _MaxPlayers; }
      set { _MaxPlayers = value; }
    }
    private readonly global::System.Collections.Generic.List<double> _BetStructure = new global::System.Collections.Generic.List<double>();
    [global::ProtoBuf.ProtoMember(5, Name=@"BetStructure", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<double> BetStructure
    {
      get { return _BetStructure; }
    }
  
    private readonly global::System.Collections.Generic.List<double> _BlindStructure = new global::System.Collections.Generic.List<double>();
    [global::ProtoBuf.ProtoMember(6, Name=@"BlindStructure", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<double> BlindStructure
    {
      get { return _BlindStructure; }
    }
  
    private readonly global::System.Collections.Generic.List<int> _PrivateCardsCount = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(7, Name=@"PrivateCardsCount", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public global::System.Collections.Generic.List<int> PrivateCardsCount
    {
      get { return _PrivateCardsCount; }
    }
  
    private readonly global::System.Collections.Generic.List<int> _PublicCardsCount = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(8, Name=@"PublicCardsCount", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public global::System.Collections.Generic.List<int> PublicCardsCount
    {
      get { return _PublicCardsCount; }
    }
  
    private readonly global::System.Collections.Generic.List<int> _SharedCardsCount = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(9, Name=@"SharedCardsCount", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public global::System.Collections.Generic.List<int> SharedCardsCount
    {
      get { return _SharedCardsCount; }
    }
  
    private readonly global::System.Collections.Generic.List<int> _BetsCountLimits = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(10, Name=@"BetsCountLimits", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public global::System.Collections.Generic.List<int> BetsCountLimits
    {
      get { return _BetsCountLimits; }
    }
  
    private readonly global::System.Collections.Generic.List<int> _FirstActor = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(11, Name=@"FirstActor", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public global::System.Collections.Generic.List<int> FirstActor
    {
      get { return _FirstActor; }
    }
  
    private readonly global::System.Collections.Generic.List<int> _FirstActorHeadsUp = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(12, Name=@"FirstActorHeadsUp", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public global::System.Collections.Generic.List<int> FirstActorHeadsUp
    {
      get { return _FirstActorHeadsUp; }
    }
  
    private ai.pkr.metabots.remote.LimitKind _LimitKind;
    [global::ProtoBuf.ProtoMember(13, IsRequired = true, Name=@"LimitKind", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public ai.pkr.metabots.remote.LimitKind LimitKind
    {
      get { return _LimitKind; }
      set { _LimitKind = value; }
    }
    private ai.pkr.metabots.remote.DeckDescriptor _DeckDescriptor;
    [global::ProtoBuf.ProtoMember(14, IsRequired = true, Name=@"DeckDescriptor", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public ai.pkr.metabots.remote.DeckDescriptor DeckDescriptor
    {
      get { return _DeckDescriptor; }
      set { _DeckDescriptor = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PlayerInfo")]
  public partial class PlayerInfo : global::ProtoBuf.IExtensible
  {
    public PlayerInfo() {}
    
    private string _Name;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"Name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string Name
    {
      get { return _Name; }
      set { _Name = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"IPlayer_OnServerDisconnect")]
  public partial class IPlayer_OnServerDisconnect : global::ProtoBuf.IExtensible
  {
    public IPlayer_OnServerDisconnect() {}
    
    private string _Reason;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"Reason", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string Reason
    {
      get { return _Reason; }
      set { _Reason = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"IPlayer_OnSessionBegin")]
  public partial class IPlayer_OnSessionBegin : global::ProtoBuf.IExtensible
  {
    public IPlayer_OnSessionBegin() {}
    
    private string _sessionName;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"sessionName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string sessionName
    {
      get { return _sessionName; }
      set { _sessionName = value; }
    }
    private ai.pkr.metabots.remote.GameDefinition _gameDef;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"gameDef", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public ai.pkr.metabots.remote.GameDefinition gameDef
    {
      get { return _gameDef; }
      set { _gameDef = value; }
    }
    private ai.pkr.metabots.remote.Props _sessionParameters;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"sessionParameters", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public ai.pkr.metabots.remote.Props sessionParameters
    {
      get { return _sessionParameters; }
      set { _sessionParameters = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"IPlayer_GameString")]
  public partial class IPlayer_GameString : global::ProtoBuf.IExtensible
  {
    public IPlayer_GameString() {}
    
    private string _GameString;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"GameString", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string GameString
    {
      get { return _GameString; }
      set { _GameString = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    [global::ProtoBuf.ProtoContract(Name=@"Ak")]
    public enum Ak
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"b", Value=0)]
      b = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"d", Value=1)]
      d = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"f", Value=2)]
      f = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"c", Value=3)]
      c = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"r", Value=4)]
      r = 4
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"LimitKind")]
    public enum LimitKind
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"FixedLimit", Value=0)]
      FixedLimit = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"PotLimit", Value=1)]
      PotLimit = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"NoLimit", Value=2)]
      NoLimit = 2
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"IPlayer_FunctionIDs")]
    public enum IPlayer_FunctionIDs
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"OnServerConnect", Value=1)]
      OnServerConnect = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"OnServerDisconnect", Value=2)]
      OnServerDisconnect = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"OnSessionBegin", Value=3)]
      OnSessionBegin = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"OnSessionEnd", Value=4)]
      OnSessionEnd = 4,
            
      [global::ProtoBuf.ProtoEnum(Name=@"OnGameBegin", Value=5)]
      OnGameBegin = 5,
            
      [global::ProtoBuf.ProtoEnum(Name=@"OnGameUpdate", Value=6)]
      OnGameUpdate = 6,
            
      [global::ProtoBuf.ProtoEnum(Name=@"OnActionRequired", Value=7)]
      OnActionRequired = 7,
            
      [global::ProtoBuf.ProtoEnum(Name=@"OnGameEnd", Value=8)]
      OnGameEnd = 8
    }
  
}